name: Validate resource pack

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main
    paths:
      - "main/**"
      - ".github/workflows/validate-resource-pack.yaml"

permissions:
  contents: read

jobs:
  validate-resource-pack:
    name: Validate resource pack
    runs-on: ubuntu-latest

    steps:
    - name: Check out merged PR
      uses: actions/checkout@v6

    - name: Check out trusted config
      uses: actions/checkout@v6
      with:
        ref: main
        path: trusted-main

    - name: Validate resource pack
      uses: MrKinau/ResourcePackValidator@v2
      with:
        resourcepack: main
        config: trusted-main/.github/workflows/config/validator_config.json
